### PR TITLE
Add Conan support

### PR DESCRIPTION
**Pull request by danimtb**
Hi!

I was reviewing your inclusion request for Conan Center and having a conanfile in the source repository is much better.

I have created an updated conanfile with the following enhancements:
- Sources are exported instead of cloning the repo (no need to clone sources as you already have them).
- Include library license in the binary packages.
- Extract library version from CMakelists.txt

I have also included a ``conan`` folder with some additional things.

- ``test_pacakge`` folder: Includes the example of you readme with conanfile.py consumer of your Conan package library. This is useful to make sure the package is correctly created.

- Conan Package Tools build script ``build.py``: This scripts generates your Conan package and gets it uploaded to your Bintray.com account (**IMPORTANT**: You would need to create a new **hidden** environment variable in Travis CI called "CONAN_PASSWORD" with you Bintray API token).

  I have included a check so only new tags on Travis are actually uploaded (new package on every new release). I have also added a new entry in the Travis matrix for this (independent from any other CI config you already had).

Hope it makes sense and do not hesitate to make any question.
Thanks!

### CODE REVIEW

**Comment by danimtb** [comment]
Seems Travis CI wasn't triggered by this PR... 🤔

**Comment by Tessil** [comment]
Hi,

Thank you very much for the review and the PR!

I was wondering though how vital the `conan` folder was? I'd like to keep the overhead in the repository to a minimal if possible and only keep the `conanfile.py` (the repo begins to have a lot of extra files outside of the sources), even if I have to upload manually the new versions from time to time. Or is it mandatory (or too bad practice) for a package in the Conan Center?


Thibaut

**Comment by danimtb** [comment]
Hi @Tessil,

Although the *conan/test_package* folder is not mandatory it is good practice when creating a Conan package. It is not only used in CI but used while debugging or updating the *conanfile.py* with new changes (especially when you add a new requirement/dependency or include a new supported platform).

I could reduce de PR and remove the *conan/test_package* folder, however, the *build.py* is needed for CI and obviously the *conanfile.py*.

Another approach would be having all the conan stuff in a separated repo and release a new branch with every release of your library.

**Comment by danimtb** [comment]
Hi @Tessil!

Please take a look at my comments above and do not hesitate to ask any further doubt or request changes and I will be happy to update this PR!

Thanks

**Comment by Tessil** [comment]
Hello,

Sorry for the delay. this week was a bit busy.

What would the procedure be to put all the Conan stuff in another repository? Should i create a `conan-tsl-hopscotch-map` repository and put the files there? 


Thanks again for your work,
Thibaut

**Comment by danimtb** [comment]
Yes, you could create a separated repository with all the Conan stuff. The *conanfile.py* has a `source()` entry to download external sources and that is usually done when packaging third party libraries (see [docopt recipe](https://github.com/conan-community/conan-docopt/blob/ea1924b850f4e46f072ed79ec9041c31d42a2391/conanfile.py#L32) for example)

This strategy of having the recipe separated from the source code is followed by many library authors 
supporting Conan, such as the Poco maintainer https://github.com/pocoproject/conan-poco

The only disadvantage about this is that you would have to bump the version of the Conan packages manually everytime you release a new version of the library, but that's all!

Hope it make sense. Thanks!

**Comment by Tessil** [comment]
Thank you for the information.

I created the [conan-tsl-hopscotch-map](https://github.com/Tessil/conan-tsl-hopscotch-map) repository and committed the necessary files. Could you check if everything seems OK?

**Comment by danimtb** [comment]
Hi @Tessil, sorry for the delay!

Yes, the new repository is looking good. It will need a run in Travis CI to verify everything is working properly. Please give it a try and let me know

**Comment by Tessil** [comment]
Hi,

Travis is run automatically and everything seems good (https://travis-ci.org/Tessil/conan-tsl-hopscotch-map/builds). I also tested the uploaded package by installing it locally without any problem.

**Comment by danimtb** [comment]
Hi,

Thanks for the link. I took a look at it and it seems the packages are not being uploaded https://travis-ci.org/Tessil/conan-tsl-hopscotch-map/builds/505452615#L675

I have created a PR in the recipe repo to fix it https://github.com/Tessil/conan-tsl-hopscotch-map/pull/1

**Comment by Tessil** [comment]
Hi,

It's uploaded only when a tag is created (so see https://travis-ci.org/Tessil/conan-tsl-hopscotch-map/builds/505441028).

I'll see to merge the other PR, though is there the documentation for `ConanMultiPackager` somewhere? A search on https://docs.conan.io returns nothing.

**Comment by danimtb** [comment]
In this case, as the recipe is separated from the source code, you can develop de recipe isolated from the source code, so you don't need to create a tag for the recipe too. It is enough having the branch.

ConanMultiPackager is under [conan-io/conan-package-tools](https://github.com/conan-io/conan-package-tools) so it is not explained in the docs and only mentioned here: https://docs.conan.io/en/latest/creating_packages/package_tools.html. However you can read the documentation in the readme of the conan-package-tools repo

**Comment by Tessil** [comment]
Yes, the tag is effectively not really necessary.

Thank you for the information. I merged your other PR, warn me if there is any problem.

**Comment by danimtb** [comment]
Thanks, @Tessil! Looking good.

I will make a final review to include the library in Conan Center and report in the other repo in case there is any further issue.

Closing this PR as obsolete.

**Pull request closed without merging**
